web:
  image: itkq/rails5
  mem_limit: 268435456
  command: ./docker-entrypoint
  ports:
    - "3000:3000"
  links:
    - db
db:
  image: mysql
  mem_limit: 268435456
  environment:
    MYSQL_ROOT_PASSWORD: password
