version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ./docker-entrypoint
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      VIRTUAL_HOST: dev.cookgram
    links:
      - db
  db:
    image: mysql
    volumes:
        - './data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
