development: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: db
  username: root
  password: password
  database: cookgram_development

test:
  <<: *default
  host: db
  username: root
  password: password
  database: cookgram_test

staging:
  <<: *default
  host: <%= ENV['STAG_DB_HOST'] %>
  username: <%= ENV['STAG_DB_USERNAME'] %>
  password: <%= ENV['STAG_DB_PASSWORD'] %>
  database: <%= ENV['STAG_DB_NAME'] %>
